/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cricketms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghufr
 */
public class Playersinfo extends javax.swing.JFrame {

    /**
     * Creates new form Playersinfo
     */
    public Playersinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("G:\\Semester_5\\prj\\Apache img\\go back.png")); // NOI18N
        jButton1.setText("Go Back");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 134, 50));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton2.setText("Show All Players Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, 50));

        jTable1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player ID", "Player Name", "Player Category", "Player Team", "Player 50's", "Player 100's", "ContactNo", "JerseyNo", "City", "PlayerHistory", "PlayerFitnessRecord", "Player type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 349, 750, 220));

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 102));
        jButton3.setText("Peshawar Zalmi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 140, 30));

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Islamabad United");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 140, 30));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton5.setText("Lahore Qalanders");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 140, 30));

        jButton6.setBackground(new java.awt.Color(51, 0, 51));
        jButton6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 0));
        jButton6.setText("Quetta Gladiators");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 140, 30));

        jButton7.setBackground(new java.awt.Color(0, 153, 204));
        jButton7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 0, 102));
        jButton7.setText("Karachi Kings");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 140, 30));

        jButton8.setBackground(new java.awt.Color(0, 102, 0));
        jButton8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 0));
        jButton8.setText("Multan Sultan");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 140, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Players");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 120, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Home/Menu/Players");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Select Team : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Check Highest No of 50's/100's");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Semester_5\\Pictures\\PLayerss.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login f2 = new login();
        f2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from players_v";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("Player_ID"));
                                        String P_NAME = String.valueOf(rs.getString("Player_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("Player_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAMname"));
                                        String P_CATEGORY = String.valueOf(rs.getString("Player_CATEGORY"));
                                        //String Play_100 = String.valueOf(rs.getInt(P_HUNDEREDS));
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("Player_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("Player_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("playercontactno"));
                                        String jersyno = String.valueOf(rs.getInt("playerjersyno"));
                                        String city = String.valueOf(rs.getString("playercity"));
                                        String phistory = String.valueOf(rs.getString("playerhistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitness"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
        /*
         try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                        //String Play_100 = String.valueOf(rs.getInt(P_HUNDEREDS));
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
        */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Peshawar Zalmi'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Islamabad United'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Lahore Qalandars'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Quetta Gladiators'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Karachi Kings'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         try {
	    			Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:gc123","system","tiger");
	    			@SuppressWarnings("deprecation")
                                      
                                       Statement st = conn.createStatement();
                                
	    			String sql="select * from PLAYERS WHERE TEAM='Multan Sultans'";
                                ResultSet rs=st.executeQuery(sql);
					
	    			
	    			while(rs.next()) {
	    				String P_ID = String.valueOf(rs.getInt("P_ID"));
                                        String P_NAME = String.valueOf(rs.getString("P_NAME"));
                                        String P_TYPE = String.valueOf(rs.getString("P_TYPE"));
                                        String TEAM = String.valueOf(rs.getString("TEAM"));
                                        String P_CATEGORY = String.valueOf(rs.getString("P_CATEGORY"));
                                       
                                        
                                        String P_HUNDEREDS = String.valueOf(rs.getInt("P_HUNDEREDS"));
                                        String P_FIFFTYS = String.valueOf(rs.getInt("P_FIFFTYS"));
                                        String contactno = String.valueOf(rs.getString("contactno"));
                                        String jersyno = String.valueOf(rs.getInt("jersyno"));
                                        String city = String.valueOf(rs.getString("city"));
                                        String phistory = String.valueOf(rs.getString("phistory"));
                                        String playerfitnessrecord = String.valueOf(rs.getString("playerfitnessrecord"));
                                        
                                        
                                        
                                        String tbData[]= {P_ID,P_NAME,P_CATEGORY,TEAM,P_FIFFTYS,P_HUNDEREDS,contactno,jersyno,city,phistory,playerfitnessrecord,P_TYPE};
                                        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
                                        
                                        tb1Model.addRow(tbData);
	    			}
	    			
	    		}catch (SQLException ex) {System.out.println(ex);
	    	}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Highest_noof50_100 f2 = new Highest_noof50_100();
        f2.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playersinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playersinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playersinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playersinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playersinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
